/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) undistort_opencv8_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};

/* undistort_point_opencv8:(u,v,fx,fy,cx,cy,k[8],p1,p2)->(xy[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[4]? arg[4][0] : 0;
  a0=(a0-a1);
  a1=arg[2]? arg[2][0] : 0;
  a0=(a0/a1);
  a1=2.;
  a2=arg[7]? arg[7][0] : 0;
  a3=(a1*a2);
  a4=(a1*a2);
  a5=(a1*a2);
  a6=(a1*a2);
  a7=(a1*a2);
  a7=(a7*a0);
  a8=arg[1]? arg[1][0] : 0;
  a9=arg[5]? arg[5][0] : 0;
  a8=(a8-a9);
  a9=arg[3]? arg[3][0] : 0;
  a8=(a8/a9);
  a7=(a7*a8);
  a9=arg[8]? arg[8][0] : 0;
  a10=casadi_sq(a0);
  a11=casadi_sq(a8);
  a10=(a10+a11);
  a11=(a1*a0);
  a11=(a11*a0);
  a11=(a10+a11);
  a11=(a9*a11);
  a7=(a7+a11);
  a7=(a0-a7);
  a11=1.;
  a12=arg[6]? arg[6][0] : 0;
  a13=(a12*a10);
  a13=(a11+a13);
  a14=arg[6]? arg[6][1] : 0;
  a15=casadi_sq(a10);
  a16=(a14*a15);
  a13=(a13+a16);
  a16=arg[6]? arg[6][2] : 0;
  a17=(a15*a10);
  a18=(a16*a17);
  a13=(a13+a18);
  a18=arg[6]? arg[6][3] : 0;
  a19=casadi_sq(a15);
  a20=(a18*a19);
  a13=(a13+a20);
  a20=arg[6]? arg[6][4] : 0;
  a21=(a20*a10);
  a21=(a21*a15);
  a13=(a13+a21);
  a21=arg[6]? arg[6][5] : 0;
  a22=(a21*a10);
  a22=(a22*a17);
  a13=(a13+a22);
  a22=arg[6]? arg[6][6] : 0;
  a23=(a22*a10);
  a23=(a23*a19);
  a13=(a13+a23);
  a23=arg[6]? arg[6][7] : 0;
  a15=(a23*a15);
  a15=(a15*a17);
  a13=(a13+a15);
  a7=(a7/a13);
  a6=(a6*a7);
  a15=(a1*a8);
  a15=(a15*a8);
  a10=(a10+a15);
  a10=(a2*a10);
  a15=(a1*a9);
  a15=(a15*a0);
  a15=(a15*a8);
  a10=(a10+a15);
  a10=(a8-a10);
  a10=(a10/a13);
  a6=(a6*a10);
  a13=casadi_sq(a7);
  a15=casadi_sq(a10);
  a13=(a13+a15);
  a15=(a1*a7);
  a15=(a15*a7);
  a15=(a13+a15);
  a15=(a9*a15);
  a6=(a6+a15);
  a6=(a0-a6);
  a15=(a12*a13);
  a15=(a11+a15);
  a17=casadi_sq(a13);
  a19=(a14*a17);
  a15=(a15+a19);
  a19=(a17*a13);
  a24=(a16*a19);
  a15=(a15+a24);
  a24=casadi_sq(a17);
  a25=(a18*a24);
  a15=(a15+a25);
  a25=(a20*a13);
  a25=(a25*a17);
  a15=(a15+a25);
  a25=(a21*a13);
  a25=(a25*a19);
  a15=(a15+a25);
  a25=(a22*a13);
  a25=(a25*a24);
  a15=(a15+a25);
  a17=(a23*a17);
  a17=(a17*a19);
  a15=(a15+a17);
  a6=(a6/a15);
  a5=(a5*a6);
  a17=(a1*a10);
  a17=(a17*a10);
  a13=(a13+a17);
  a13=(a2*a13);
  a17=(a1*a9);
  a17=(a17*a7);
  a17=(a17*a10);
  a13=(a13+a17);
  a13=(a8-a13);
  a13=(a13/a15);
  a5=(a5*a13);
  a15=casadi_sq(a6);
  a17=casadi_sq(a13);
  a15=(a15+a17);
  a17=(a1*a6);
  a17=(a17*a6);
  a17=(a15+a17);
  a17=(a9*a17);
  a5=(a5+a17);
  a5=(a0-a5);
  a17=(a12*a15);
  a17=(a11+a17);
  a10=casadi_sq(a15);
  a7=(a14*a10);
  a17=(a17+a7);
  a7=(a10*a15);
  a19=(a16*a7);
  a17=(a17+a19);
  a19=casadi_sq(a10);
  a25=(a18*a19);
  a17=(a17+a25);
  a25=(a20*a15);
  a25=(a25*a10);
  a17=(a17+a25);
  a25=(a21*a15);
  a25=(a25*a7);
  a17=(a17+a25);
  a25=(a22*a15);
  a25=(a25*a19);
  a17=(a17+a25);
  a10=(a23*a10);
  a10=(a10*a7);
  a17=(a17+a10);
  a5=(a5/a17);
  a4=(a4*a5);
  a10=(a1*a13);
  a10=(a10*a13);
  a15=(a15+a10);
  a15=(a2*a15);
  a10=(a1*a9);
  a10=(a10*a6);
  a10=(a10*a13);
  a15=(a15+a10);
  a15=(a8-a15);
  a15=(a15/a17);
  a4=(a4*a15);
  a17=casadi_sq(a5);
  a10=casadi_sq(a15);
  a17=(a17+a10);
  a10=(a1*a5);
  a10=(a10*a5);
  a10=(a17+a10);
  a10=(a9*a10);
  a4=(a4+a10);
  a4=(a0-a4);
  a10=(a12*a17);
  a10=(a11+a10);
  a13=casadi_sq(a17);
  a6=(a14*a13);
  a10=(a10+a6);
  a6=(a13*a17);
  a7=(a16*a6);
  a10=(a10+a7);
  a7=casadi_sq(a13);
  a25=(a18*a7);
  a10=(a10+a25);
  a25=(a20*a17);
  a25=(a25*a13);
  a10=(a10+a25);
  a25=(a21*a17);
  a25=(a25*a6);
  a10=(a10+a25);
  a25=(a22*a17);
  a25=(a25*a7);
  a10=(a10+a25);
  a13=(a23*a13);
  a13=(a13*a6);
  a10=(a10+a13);
  a4=(a4/a10);
  a3=(a3*a4);
  a13=(a1*a15);
  a13=(a13*a15);
  a17=(a17+a13);
  a17=(a2*a17);
  a13=(a1*a9);
  a13=(a13*a5);
  a13=(a13*a15);
  a17=(a17+a13);
  a17=(a8-a17);
  a17=(a17/a10);
  a3=(a3*a17);
  a10=casadi_sq(a4);
  a13=casadi_sq(a17);
  a10=(a10+a13);
  a13=(a1*a4);
  a13=(a13*a4);
  a13=(a10+a13);
  a13=(a9*a13);
  a3=(a3+a13);
  a0=(a0-a3);
  a12=(a12*a10);
  a11=(a11+a12);
  a12=casadi_sq(a10);
  a14=(a14*a12);
  a11=(a11+a14);
  a14=(a12*a10);
  a16=(a16*a14);
  a11=(a11+a16);
  a16=casadi_sq(a12);
  a18=(a18*a16);
  a11=(a11+a18);
  a20=(a20*a10);
  a20=(a20*a12);
  a11=(a11+a20);
  a21=(a21*a10);
  a21=(a21*a14);
  a11=(a11+a21);
  a22=(a22*a10);
  a22=(a22*a16);
  a11=(a11+a22);
  a23=(a23*a12);
  a23=(a23*a14);
  a11=(a11+a23);
  a0=(a0/a11);
  if (res[0]!=0) res[0][0]=a0;
  a0=(a1*a17);
  a0=(a0*a17);
  a10=(a10+a0);
  a2=(a2*a10);
  a1=(a1*a9);
  a1=(a1*a4);
  a1=(a1*a17);
  a2=(a2+a1);
  a8=(a8-a2);
  a8=(a8/a11);
  if (res[0]!=0) res[0][1]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int undistort_point_opencv8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int undistort_point_opencv8_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int undistort_point_opencv8_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void undistort_point_opencv8_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int undistort_point_opencv8_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void undistort_point_opencv8_release(int mem) {
}

CASADI_SYMBOL_EXPORT void undistort_point_opencv8_incref(void) {
}

CASADI_SYMBOL_EXPORT void undistort_point_opencv8_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int undistort_point_opencv8_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int undistort_point_opencv8_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real undistort_point_opencv8_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* undistort_point_opencv8_name_in(casadi_int i) {
  switch (i) {
    case 0: return "u";
    case 1: return "v";
    case 2: return "fx";
    case 3: return "fy";
    case 4: return "cx";
    case 5: return "cy";
    case 6: return "k";
    case 7: return "p1";
    case 8: return "p2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* undistort_point_opencv8_name_out(casadi_int i) {
  switch (i) {
    case 0: return "xy";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* undistort_point_opencv8_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s1;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* undistort_point_opencv8_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int undistort_point_opencv8_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int undistort_point_opencv8_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
