/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int J_alloc_mem(void);
int J_init_mem(int mem);
void J_free_mem(int mem);
int J_checkout(void);
void J_release(int mem);
void J_incref(void);
void J_decref(void);
casadi_int J_n_in(void);
casadi_int J_n_out(void);
casadi_real J_default_in(casadi_int i);
const char* J_name_in(casadi_int i);
const char* J_name_out(casadi_int i);
const casadi_int* J_sparsity_in(casadi_int i);
const casadi_int* J_sparsity_out(casadi_int i);
int J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_SZ_ARG 10
#define J_SZ_RES 1
#define J_SZ_IW 0
#define J_SZ_W 172
int grad_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int grad_J_alloc_mem(void);
int grad_J_init_mem(int mem);
void grad_J_free_mem(int mem);
int grad_J_checkout(void);
void grad_J_release(int mem);
void grad_J_incref(void);
void grad_J_decref(void);
casadi_int grad_J_n_in(void);
casadi_int grad_J_n_out(void);
casadi_real grad_J_default_in(casadi_int i);
const char* grad_J_name_in(casadi_int i);
const char* grad_J_name_out(casadi_int i);
const casadi_int* grad_J_sparsity_in(casadi_int i);
const casadi_int* grad_J_sparsity_out(casadi_int i);
int grad_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int grad_J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define grad_J_SZ_ARG 10
#define grad_J_SZ_RES 1
#define grad_J_SZ_IW 0
#define grad_J_SZ_W 350
int hess_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int hess_J_alloc_mem(void);
int hess_J_init_mem(int mem);
void hess_J_free_mem(int mem);
int hess_J_checkout(void);
void hess_J_release(int mem);
void hess_J_incref(void);
void hess_J_decref(void);
casadi_int hess_J_n_in(void);
casadi_int hess_J_n_out(void);
casadi_real hess_J_default_in(casadi_int i);
const char* hess_J_name_in(casadi_int i);
const char* hess_J_name_out(casadi_int i);
const casadi_int* hess_J_sparsity_in(casadi_int i);
const casadi_int* hess_J_sparsity_out(casadi_int i);
int hess_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int hess_J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define hess_J_SZ_ARG 10
#define hess_J_SZ_RES 1
#define hess_J_SZ_IW 0
#define hess_J_SZ_W 992
#ifdef __cplusplus
} /* extern "C" */
#endif
