/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) grad_J_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[18] = {4, 3, 0, 4, 8, 12, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s4[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};

/* grad_J:(i0[3],i1,i2,i3,i4,i5[4x4],i6[4x3],i7[2x3])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[5]? arg[5][11] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[5]? arg[5][12] : 0;
  a4=(a2*a3);
  a5=sin(a1);
  a6=arg[5]? arg[5][13] : 0;
  a7=(a5*a6);
  a4=(a4-a7);
  a7=arg[0]? arg[0][0] : 0;
  a8=arg[5]? arg[5][15] : 0;
  a9=(a7*a8);
  a4=(a4+a9);
  a9=arg[5]? arg[5][0] : 0;
  a10=(a2*a9);
  a11=arg[5]? arg[5][1] : 0;
  a12=(a5*a11);
  a10=(a10-a12);
  a12=arg[5]? arg[5][3] : 0;
  a13=(a7*a12);
  a10=(a10+a13);
  a13=casadi_sq(a10);
  a14=(a5*a9);
  a15=(a2*a11);
  a14=(a14+a15);
  a15=arg[0]? arg[0][1] : 0;
  a16=(a15*a12);
  a14=(a14+a16);
  a16=casadi_sq(a14);
  a13=(a13+a16);
  a16=arg[5]? arg[5][2] : 0;
  a17=casadi_sq(a16);
  a13=(a13+a17);
  a17=casadi_sq(a12);
  a13=(a13+a17);
  a13=sqrt(a13);
  a17=(a10/a13);
  a18=(a4*a17);
  a19=(a5*a3);
  a20=(a2*a6);
  a19=(a19+a20);
  a20=(a15*a8);
  a19=(a19+a20);
  a20=(a14/a13);
  a21=(a19*a20);
  a18=(a18+a21);
  a21=arg[5]? arg[5][14] : 0;
  a16=(a16/a13);
  a22=(a21*a16);
  a18=(a18+a22);
  a22=(a12/a13);
  a23=(a8*a22);
  a18=(a18+a23);
  a23=(a18*a17);
  a23=(a4-a23);
  a24=arg[5]? arg[5][4] : 0;
  a25=(a2*a24);
  a26=arg[5]? arg[5][5] : 0;
  a27=(a5*a26);
  a25=(a25-a27);
  a27=arg[5]? arg[5][7] : 0;
  a28=(a7*a27);
  a25=(a25+a28);
  a28=(a25*a17);
  a29=(a5*a24);
  a30=(a2*a26);
  a29=(a29+a30);
  a30=(a15*a27);
  a29=(a29+a30);
  a30=(a29*a20);
  a28=(a28+a30);
  a30=arg[5]? arg[5][6] : 0;
  a31=(a30*a16);
  a28=(a28+a31);
  a31=(a27*a22);
  a28=(a28+a31);
  a31=(a28*a17);
  a31=(a25-a31);
  a32=casadi_sq(a31);
  a33=(a28*a20);
  a33=(a29-a33);
  a34=casadi_sq(a33);
  a32=(a32+a34);
  a34=(a28*a16);
  a34=(a30-a34);
  a35=casadi_sq(a34);
  a32=(a32+a35);
  a35=(a28*a22);
  a35=(a27-a35);
  a36=casadi_sq(a35);
  a32=(a32+a36);
  a32=sqrt(a32);
  a36=(a31/a32);
  a37=(a23*a36);
  a38=(a18*a20);
  a38=(a19-a38);
  a39=(a33/a32);
  a40=(a38*a39);
  a37=(a37+a40);
  a40=(a18*a16);
  a40=(a21-a40);
  a41=(a34/a32);
  a42=(a40*a41);
  a37=(a37+a42);
  a42=(a18*a22);
  a42=(a8-a42);
  a43=(a35/a32);
  a44=(a42*a43);
  a37=(a37+a44);
  a44=(a37*a36);
  a44=(a23-a44);
  a45=(a37*a43);
  a45=(a42-a45);
  a46=arg[5]? arg[5][8] : 0;
  a47=(a2*a46);
  a48=arg[5]? arg[5][9] : 0;
  a49=(a5*a48);
  a47=(a47-a49);
  a7=(a7*a0);
  a47=(a47+a7);
  a7=(a47*a17);
  a5=(a5*a46);
  a2=(a2*a48);
  a5=(a5+a2);
  a15=(a15*a0);
  a5=(a5+a15);
  a15=(a5*a20);
  a7=(a7+a15);
  a15=arg[5]? arg[5][10] : 0;
  a2=(a15*a16);
  a7=(a7+a2);
  a2=(a0*a22);
  a7=(a7+a2);
  a2=(a7*a17);
  a2=(a47-a2);
  a49=(a2*a36);
  a50=(a7*a20);
  a50=(a5-a50);
  a51=(a50*a39);
  a49=(a49+a51);
  a51=(a7*a16);
  a51=(a15-a51);
  a52=(a51*a41);
  a49=(a49+a52);
  a52=(a7*a22);
  a52=(a0-a52);
  a53=(a52*a43);
  a49=(a49+a53);
  a53=(a49*a36);
  a53=(a2-a53);
  a54=casadi_sq(a53);
  a55=(a49*a39);
  a55=(a50-a55);
  a56=casadi_sq(a55);
  a54=(a54+a56);
  a56=(a49*a41);
  a56=(a51-a56);
  a57=casadi_sq(a56);
  a54=(a54+a57);
  a57=(a49*a43);
  a57=(a52-a57);
  a58=casadi_sq(a57);
  a54=(a54+a58);
  a54=sqrt(a54);
  a58=(a53/a54);
  a59=(a44*a58);
  a60=(a37*a39);
  a60=(a38-a60);
  a61=(a55/a54);
  a62=(a60*a61);
  a59=(a59+a62);
  a62=(a37*a41);
  a62=(a40-a62);
  a63=(a56/a54);
  a64=(a62*a63);
  a59=(a59+a64);
  a64=(a57/a54);
  a65=(a45*a64);
  a59=(a59+a65);
  a65=(a59*a64);
  a65=(a45-a65);
  a66=(a59*a58);
  a66=(a44-a66);
  a67=casadi_sq(a66);
  a68=(a59*a61);
  a68=(a60-a68);
  a69=casadi_sq(a68);
  a67=(a67+a69);
  a69=(a59*a63);
  a69=(a62-a69);
  a70=casadi_sq(a69);
  a67=(a67+a70);
  a70=casadi_sq(a65);
  a67=(a67+a70);
  a67=sqrt(a67);
  a70=(a65/a67);
  a71=(a70/a67);
  a72=arg[6]? arg[6][11] : 0;
  a73=(a66/a67);
  a74=(a73/a67);
  a75=(a37*a74);
  a75=(a36-a75);
  a76=(a59*a74);
  a76=(a58-a76);
  a76=(a76/a54);
  a77=(a49*a76);
  a75=(a75-a77);
  a75=(a75/a32);
  a77=arg[6]? arg[6][8] : 0;
  a78=(a75*a77);
  a79=(a68/a67);
  a80=(a79/a67);
  a81=(a37*a80);
  a81=(a39-a81);
  a82=(a59*a80);
  a82=(a61-a82);
  a82=(a82/a54);
  a83=(a49*a82);
  a81=(a81-a83);
  a81=(a81/a32);
  a83=arg[6]? arg[6][9] : 0;
  a84=(a81*a83);
  a78=(a78+a84);
  a84=(a69/a67);
  a85=(a84/a67);
  a86=(a37*a85);
  a86=(a41-a86);
  a87=(a59*a85);
  a87=(a63-a87);
  a87=(a87/a54);
  a88=(a49*a87);
  a86=(a86-a88);
  a86=(a86/a32);
  a88=arg[6]? arg[6][10] : 0;
  a89=(a86*a88);
  a78=(a78+a89);
  a89=(a37*a71);
  a89=(a43-a89);
  a90=(a59*a71);
  a90=(a64-a90);
  a90=(a90/a54);
  a91=(a49*a90);
  a89=(a89-a91);
  a89=(a89/a32);
  a91=(a89*a72);
  a78=(a78+a91);
  a91=(a76*a77);
  a92=(a82*a83);
  a91=(a91+a92);
  a92=(a87*a88);
  a91=(a91+a92);
  a92=(a90*a72);
  a91=(a91+a92);
  a78=(a78/a91);
  a92=(a78/a91);
  a93=arg[2]? arg[2][0] : 0;
  a78=(a93*a78);
  a94=arg[4]? arg[4][0] : 0;
  a78=(a78+a94);
  a95=arg[7]? arg[7][5] : 0;
  a78=(a78-a95);
  a78=(a78+a78);
  a78=(a93*a78);
  a92=(a92*a78);
  a95=(a18*a74);
  a95=(a17-a95);
  a96=(a7*a76);
  a95=(a95-a96);
  a96=(a28*a75);
  a95=(a95-a96);
  a95=(a95/a13);
  a96=(a95*a77);
  a97=(a18*a80);
  a97=(a20-a97);
  a98=(a7*a82);
  a97=(a97-a98);
  a98=(a28*a81);
  a97=(a97-a98);
  a97=(a97/a13);
  a98=(a97*a83);
  a96=(a96+a98);
  a98=(a18*a85);
  a98=(a16-a98);
  a99=(a7*a87);
  a98=(a98-a99);
  a99=(a28*a86);
  a98=(a98-a99);
  a98=(a98/a13);
  a99=(a98*a88);
  a96=(a96+a99);
  a99=(a18*a71);
  a99=(a22-a99);
  a100=(a7*a90);
  a99=(a99-a100);
  a100=(a28*a89);
  a99=(a99-a100);
  a99=(a99/a13);
  a100=(a99*a72);
  a96=(a96+a100);
  a96=(a96/a91);
  a100=(a96/a91);
  a101=arg[1]? arg[1][0] : 0;
  a96=(a101*a96);
  a102=arg[3]? arg[3][0] : 0;
  a96=(a96+a102);
  a103=arg[7]? arg[7][4] : 0;
  a96=(a96-a103);
  a96=(a96+a96);
  a96=(a101*a96);
  a100=(a100*a96);
  a92=(a92+a100);
  a100=(a72*a92);
  a103=arg[6]? arg[6][7] : 0;
  a104=arg[6]? arg[6][4] : 0;
  a105=(a75*a104);
  a106=arg[6]? arg[6][5] : 0;
  a107=(a81*a106);
  a105=(a105+a107);
  a107=arg[6]? arg[6][6] : 0;
  a108=(a86*a107);
  a105=(a105+a108);
  a108=(a89*a103);
  a105=(a105+a108);
  a108=(a76*a104);
  a109=(a82*a106);
  a108=(a108+a109);
  a109=(a87*a107);
  a108=(a108+a109);
  a109=(a90*a103);
  a108=(a108+a109);
  a105=(a105/a108);
  a109=(a105/a108);
  a105=(a93*a105);
  a105=(a105+a94);
  a110=arg[7]? arg[7][3] : 0;
  a105=(a105-a110);
  a105=(a105+a105);
  a105=(a93*a105);
  a109=(a109*a105);
  a110=(a95*a104);
  a111=(a97*a106);
  a110=(a110+a111);
  a111=(a98*a107);
  a110=(a110+a111);
  a111=(a99*a103);
  a110=(a110+a111);
  a110=(a110/a108);
  a111=(a110/a108);
  a110=(a101*a110);
  a110=(a110+a102);
  a112=arg[7]? arg[7][2] : 0;
  a110=(a110-a112);
  a110=(a110+a110);
  a110=(a101*a110);
  a111=(a111*a110);
  a109=(a109+a111);
  a111=(a103*a109);
  a100=(a100+a111);
  a111=arg[6]? arg[6][3] : 0;
  a112=arg[6]? arg[6][0] : 0;
  a113=(a75*a112);
  a114=arg[6]? arg[6][1] : 0;
  a115=(a81*a114);
  a113=(a113+a115);
  a115=arg[6]? arg[6][2] : 0;
  a116=(a86*a115);
  a113=(a113+a116);
  a116=(a89*a111);
  a113=(a113+a116);
  a116=(a76*a112);
  a117=(a82*a114);
  a116=(a116+a117);
  a117=(a87*a115);
  a116=(a116+a117);
  a117=(a90*a111);
  a116=(a116+a117);
  a113=(a113/a116);
  a117=(a113/a116);
  a113=(a93*a113);
  a113=(a113+a94);
  a94=arg[7]? arg[7][1] : 0;
  a113=(a113-a94);
  a113=(a113+a113);
  a93=(a93*a113);
  a117=(a117*a93);
  a113=(a95*a112);
  a94=(a97*a114);
  a113=(a113+a94);
  a94=(a98*a115);
  a113=(a113+a94);
  a94=(a99*a111);
  a113=(a113+a94);
  a113=(a113/a116);
  a94=(a113/a116);
  a113=(a101*a113);
  a113=(a113+a102);
  a102=arg[7]? arg[7][0] : 0;
  a113=(a113-a102);
  a113=(a113+a113);
  a101=(a101*a113);
  a94=(a94*a101);
  a117=(a117+a94);
  a94=(a111*a117);
  a100=(a100+a94);
  a78=(a78/a91);
  a94=(a72*a78);
  a105=(a105/a108);
  a113=(a103*a105);
  a94=(a94+a113);
  a93=(a93/a116);
  a113=(a111*a93);
  a94=(a94+a113);
  a96=(a96/a91);
  a72=(a72*a96);
  a110=(a110/a108);
  a103=(a103*a110);
  a72=(a72+a103);
  a101=(a101/a116);
  a111=(a111*a101);
  a72=(a72+a111);
  a111=(a72/a13);
  a116=(a28*a111);
  a94=(a94-a116);
  a116=(a94/a32);
  a103=(a49*a116);
  a100=(a100+a103);
  a103=(a7*a111);
  a100=(a100+a103);
  a103=(a100/a54);
  a108=(a71*a103);
  a91=(a88*a92);
  a113=(a107*a109);
  a91=(a91+a113);
  a113=(a115*a117);
  a91=(a91+a113);
  a113=(a88*a78);
  a102=(a107*a105);
  a113=(a113+a102);
  a102=(a115*a93);
  a113=(a113+a102);
  a88=(a88*a96);
  a107=(a107*a110);
  a88=(a88+a107);
  a115=(a115*a101);
  a88=(a88+a115);
  a115=(a88/a13);
  a107=(a28*a115);
  a113=(a113-a107);
  a107=(a113/a32);
  a102=(a49*a107);
  a91=(a91+a102);
  a102=(a7*a115);
  a91=(a91+a102);
  a102=(a91/a54);
  a118=(a85*a102);
  a108=(a108+a118);
  a118=(a83*a92);
  a119=(a106*a109);
  a118=(a118+a119);
  a119=(a114*a117);
  a118=(a118+a119);
  a119=(a83*a78);
  a120=(a106*a105);
  a119=(a119+a120);
  a120=(a114*a93);
  a119=(a119+a120);
  a83=(a83*a96);
  a106=(a106*a110);
  a83=(a83+a106);
  a114=(a114*a101);
  a83=(a83+a114);
  a114=(a83/a13);
  a106=(a28*a114);
  a119=(a119-a106);
  a106=(a119/a32);
  a120=(a49*a106);
  a118=(a118+a120);
  a120=(a7*a114);
  a118=(a118+a120);
  a120=(a118/a54);
  a121=(a80*a120);
  a108=(a108+a121);
  a92=(a77*a92);
  a109=(a104*a109);
  a92=(a92+a109);
  a117=(a112*a117);
  a92=(a92+a117);
  a78=(a77*a78);
  a105=(a104*a105);
  a78=(a78+a105);
  a93=(a112*a93);
  a78=(a78+a93);
  a77=(a77*a96);
  a104=(a104*a110);
  a77=(a77+a104);
  a112=(a112*a101);
  a77=(a77+a112);
  a112=(a77/a13);
  a101=(a28*a112);
  a78=(a78-a101);
  a101=(a78/a32);
  a104=(a49*a101);
  a92=(a92+a104);
  a104=(a7*a112);
  a92=(a92+a104);
  a104=(a92/a54);
  a110=(a74*a104);
  a108=(a108+a110);
  a110=(a59*a103);
  a96=(a37*a116);
  a110=(a110-a96);
  a96=(a18*a111);
  a110=(a110-a96);
  a96=(a110/a67);
  a93=(a96/a67);
  a65=(a65+a65);
  a105=(a71/a67);
  a105=(a105*a110);
  a70=(a70/a67);
  a70=(a70*a96);
  a105=(a105+a70);
  a70=(a85/a67);
  a96=(a59*a102);
  a110=(a37*a107);
  a96=(a96-a110);
  a110=(a18*a115);
  a96=(a96-a110);
  a70=(a70*a96);
  a105=(a105+a70);
  a84=(a84/a67);
  a96=(a96/a67);
  a84=(a84*a96);
  a105=(a105+a84);
  a84=(a80/a67);
  a70=(a59*a120);
  a110=(a37*a106);
  a70=(a70-a110);
  a110=(a18*a114);
  a70=(a70-a110);
  a84=(a84*a70);
  a105=(a105+a84);
  a79=(a79/a67);
  a70=(a70/a67);
  a79=(a79*a70);
  a105=(a105+a79);
  a79=(a74/a67);
  a84=(a59*a104);
  a110=(a37*a101);
  a84=(a84-a110);
  a110=(a18*a112);
  a84=(a84-a110);
  a79=(a79*a84);
  a105=(a105+a79);
  a73=(a73/a67);
  a84=(a84/a67);
  a73=(a73*a84);
  a105=(a105+a73);
  a73=(a67+a67);
  a105=(a105/a73);
  a65=(a65*a105);
  a93=(a93-a65);
  a65=(a64*a93);
  a108=(a108-a65);
  a96=(a96/a67);
  a69=(a69+a69);
  a69=(a69*a105);
  a96=(a96-a69);
  a69=(a63*a96);
  a108=(a108-a69);
  a70=(a70/a67);
  a68=(a68+a68);
  a68=(a68*a105);
  a70=(a70-a68);
  a68=(a61*a70);
  a108=(a108-a68);
  a84=(a84/a67);
  a66=(a66+a66);
  a66=(a66*a105);
  a84=(a84-a66);
  a66=(a58*a84);
  a108=(a108-a66);
  a44=(a44*a108);
  a66=(a59*a84);
  a104=(a104+a66);
  a44=(a44-a104);
  a104=(a44/a54);
  a53=(a53+a53);
  a66=(a90/a54);
  a66=(a66*a100);
  a100=(a87/a54);
  a100=(a100*a91);
  a66=(a66+a100);
  a100=(a82/a54);
  a100=(a100*a118);
  a66=(a66+a100);
  a100=(a76/a54);
  a100=(a100*a92);
  a66=(a66+a100);
  a100=(a64/a54);
  a45=(a45*a108);
  a92=(a59*a93);
  a103=(a103+a92);
  a45=(a45-a103);
  a100=(a100*a45);
  a66=(a66-a100);
  a100=(a63/a54);
  a62=(a62*a108);
  a103=(a59*a96);
  a102=(a102+a103);
  a62=(a62-a102);
  a100=(a100*a62);
  a66=(a66-a100);
  a100=(a61/a54);
  a60=(a60*a108);
  a59=(a59*a70);
  a120=(a120+a59);
  a60=(a60-a120);
  a100=(a100*a60);
  a66=(a66-a100);
  a100=(a58/a54);
  a100=(a100*a44);
  a66=(a66-a100);
  a100=(a54+a54);
  a66=(a66/a100);
  a53=(a53*a66);
  a104=(a104+a53);
  a53=(a90*a116);
  a100=(a87*a107);
  a53=(a53+a100);
  a100=(a82*a106);
  a53=(a53+a100);
  a100=(a76*a101);
  a53=(a53+a100);
  a45=(a45/a54);
  a57=(a57+a57);
  a57=(a57*a66);
  a45=(a45+a57);
  a57=(a43*a45);
  a53=(a53+a57);
  a62=(a62/a54);
  a56=(a56+a56);
  a56=(a56*a66);
  a62=(a62+a56);
  a56=(a41*a62);
  a53=(a53+a56);
  a60=(a60/a54);
  a55=(a55+a55);
  a55=(a55*a66);
  a60=(a60+a55);
  a55=(a39*a60);
  a53=(a53+a55);
  a55=(a36*a104);
  a53=(a53+a55);
  a55=(a36*a53);
  a55=(a104-a55);
  a90=(a90*a111);
  a87=(a87*a115);
  a90=(a90+a87);
  a82=(a82*a114);
  a90=(a90+a82);
  a76=(a76*a112);
  a90=(a90+a76);
  a76=(a43*a53);
  a76=(a45-a76);
  a82=(a22*a76);
  a90=(a90+a82);
  a82=(a41*a53);
  a82=(a62-a82);
  a87=(a16*a82);
  a90=(a90+a87);
  a87=(a39*a53);
  a87=(a60-a87);
  a66=(a20*a87);
  a90=(a90+a66);
  a66=(a17*a55);
  a90=(a90+a66);
  a66=(a17*a90);
  a66=(a55-a66);
  a54=(a0*a66);
  a104=(a49*a104);
  a104=(a101-a104);
  a2=(a2*a53);
  a104=(a104-a2);
  a58=(a58*a108);
  a84=(a84+a58);
  a58=(a37*a84);
  a104=(a104-a58);
  a58=(a71*a116);
  a2=(a85*a107);
  a58=(a58+a2);
  a2=(a80*a106);
  a58=(a58+a2);
  a101=(a74*a101);
  a58=(a58+a101);
  a64=(a64*a108);
  a93=(a93+a64);
  a64=(a43*a93);
  a58=(a58+a64);
  a63=(a63*a108);
  a96=(a96+a63);
  a63=(a41*a96);
  a58=(a58+a63);
  a61=(a61*a108);
  a70=(a70+a61);
  a61=(a39*a70);
  a58=(a58+a61);
  a61=(a36*a84);
  a58=(a58+a61);
  a23=(a23*a58);
  a104=(a104-a23);
  a23=(a104/a32);
  a31=(a31+a31);
  a61=(a89/a32);
  a61=(a61*a94);
  a94=(a86/a32);
  a94=(a94*a113);
  a61=(a61+a94);
  a94=(a81/a32);
  a94=(a94*a119);
  a61=(a61+a94);
  a94=(a75/a32);
  a94=(a94*a78);
  a61=(a61+a94);
  a94=(a43/a32);
  a78=(a37*a93);
  a116=(a116-a78);
  a45=(a49*a45);
  a116=(a116-a45);
  a52=(a52*a53);
  a116=(a116-a52);
  a42=(a42*a58);
  a116=(a116-a42);
  a94=(a94*a116);
  a61=(a61+a94);
  a94=(a41/a32);
  a42=(a37*a96);
  a107=(a107-a42);
  a62=(a49*a62);
  a107=(a107-a62);
  a51=(a51*a53);
  a107=(a107-a51);
  a40=(a40*a58);
  a107=(a107-a40);
  a94=(a94*a107);
  a61=(a61+a94);
  a94=(a39/a32);
  a37=(a37*a70);
  a106=(a106-a37);
  a49=(a49*a60);
  a106=(a106-a49);
  a50=(a50*a53);
  a106=(a106-a50);
  a38=(a38*a58);
  a106=(a106-a38);
  a94=(a94*a106);
  a61=(a61+a94);
  a94=(a36/a32);
  a94=(a94*a104);
  a61=(a61+a94);
  a94=(a32+a32);
  a61=(a61/a94);
  a31=(a31*a61);
  a23=(a23-a31);
  a89=(a89*a111);
  a86=(a86*a115);
  a89=(a89+a86);
  a81=(a81*a114);
  a89=(a89+a81);
  a75=(a75*a112);
  a89=(a89+a75);
  a116=(a116/a32);
  a35=(a35+a35);
  a35=(a35*a61);
  a116=(a116-a35);
  a35=(a22*a116);
  a89=(a89+a35);
  a107=(a107/a32);
  a34=(a34+a34);
  a34=(a34*a61);
  a107=(a107-a34);
  a34=(a16*a107);
  a89=(a89+a34);
  a106=(a106/a32);
  a33=(a33+a33);
  a33=(a33*a61);
  a106=(a106-a33);
  a33=(a20*a106);
  a89=(a89+a33);
  a33=(a17*a23);
  a89=(a89+a33);
  a33=(a17*a89);
  a33=(a23-a33);
  a61=(a27*a33);
  a54=(a54+a61);
  a36=(a36*a58);
  a84=(a84-a36);
  a71=(a71*a111);
  a85=(a85*a115);
  a71=(a71+a85);
  a80=(a80*a114);
  a71=(a71+a80);
  a74=(a74*a112);
  a71=(a71+a74);
  a43=(a43*a58);
  a93=(a93-a43);
  a43=(a22*a93);
  a71=(a71+a43);
  a41=(a41*a58);
  a96=(a96-a41);
  a41=(a16*a96);
  a71=(a71+a41);
  a39=(a39*a58);
  a70=(a70-a39);
  a39=(a20*a70);
  a71=(a71+a39);
  a39=(a17*a84);
  a71=(a71+a39);
  a39=(a17*a71);
  a39=(a84-a39);
  a58=(a8*a39);
  a54=(a54+a58);
  a55=(a7*a55);
  a112=(a112-a55);
  a47=(a47*a90);
  a112=(a112-a47);
  a23=(a28*a23);
  a112=(a112-a23);
  a25=(a25*a89);
  a112=(a112-a25);
  a84=(a18*a84);
  a112=(a112-a84);
  a4=(a4*a71);
  a112=(a112-a4);
  a4=(a112/a13);
  a10=(a10+a10);
  a99=(a99/a13);
  a99=(a99*a72);
  a98=(a98/a13);
  a98=(a98*a88);
  a99=(a99+a98);
  a97=(a97/a13);
  a97=(a97*a83);
  a99=(a99+a97);
  a95=(a95/a13);
  a95=(a95*a77);
  a99=(a99+a95);
  a22=(a22/a13);
  a76=(a7*a76);
  a111=(a111-a76);
  a76=(a0*a90);
  a111=(a111-a76);
  a93=(a18*a93);
  a111=(a111-a93);
  a116=(a28*a116);
  a111=(a111-a116);
  a116=(a27*a89);
  a111=(a111-a116);
  a116=(a8*a71);
  a111=(a111-a116);
  a22=(a22*a111);
  a99=(a99+a22);
  a16=(a16/a13);
  a82=(a7*a82);
  a115=(a115-a82);
  a15=(a15*a90);
  a115=(a115-a15);
  a96=(a18*a96);
  a115=(a115-a96);
  a107=(a28*a107);
  a115=(a115-a107);
  a30=(a30*a89);
  a115=(a115-a30);
  a21=(a21*a71);
  a115=(a115-a21);
  a16=(a16*a115);
  a99=(a99+a16);
  a16=(a20/a13);
  a7=(a7*a87);
  a114=(a114-a7);
  a5=(a5*a90);
  a114=(a114-a5);
  a18=(a18*a70);
  a114=(a114-a18);
  a28=(a28*a106);
  a114=(a114-a28);
  a29=(a29*a89);
  a114=(a114-a29);
  a19=(a19*a71);
  a114=(a114-a19);
  a16=(a16*a114);
  a99=(a99+a16);
  a17=(a17/a13);
  a17=(a17*a112);
  a99=(a99+a17);
  a17=(a13+a13);
  a99=(a99/a17);
  a10=(a10*a99);
  a4=(a4-a10);
  a10=(a12*a4);
  a54=(a54+a10);
  if (res[0]!=0) res[0][0]=a54;
  a90=(a20*a90);
  a87=(a87-a90);
  a0=(a0*a87);
  a89=(a20*a89);
  a106=(a106-a89);
  a27=(a27*a106);
  a0=(a0+a27);
  a20=(a20*a71);
  a70=(a70-a20);
  a8=(a8*a70);
  a0=(a0+a8);
  a114=(a114/a13);
  a14=(a14+a14);
  a14=(a14*a99);
  a114=(a114-a14);
  a12=(a12*a114);
  a0=(a0+a12);
  if (res[0]!=0) res[0][1]=a0;
  a0=cos(a1);
  a12=(a46*a87);
  a14=(a48*a66);
  a12=(a12-a14);
  a14=(a24*a106);
  a12=(a12+a14);
  a14=(a26*a33);
  a12=(a12-a14);
  a14=(a3*a70);
  a12=(a12+a14);
  a14=(a6*a39);
  a12=(a12-a14);
  a14=(a9*a114);
  a12=(a12+a14);
  a14=(a11*a4);
  a12=(a12-a14);
  a0=(a0*a12);
  a1=sin(a1);
  a48=(a48*a87);
  a46=(a46*a66);
  a48=(a48+a46);
  a26=(a26*a106);
  a48=(a48+a26);
  a24=(a24*a33);
  a48=(a48+a24);
  a6=(a6*a70);
  a48=(a48+a6);
  a3=(a3*a39);
  a48=(a48+a3);
  a11=(a11*a114);
  a48=(a48+a11);
  a9=(a9*a4);
  a48=(a48+a9);
  a1=(a1*a48);
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int grad_J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void grad_J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int grad_J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void grad_J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void grad_J_incref(void) {
}

CASADI_SYMBOL_EXPORT void grad_J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int grad_J_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int grad_J_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real grad_J_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* grad_J_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* grad_J_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* grad_J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s2;
    case 6: return casadi_s3;
    case 7: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* grad_J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int grad_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
