/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) grad_J_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};

/* grad_J:(i0[3],i1,i2,i3,i4,i5[4x4])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[5]? arg[5][11] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[5]? arg[5][12] : 0;
  a4=(a2*a3);
  a5=sin(a1);
  a6=arg[5]? arg[5][13] : 0;
  a7=(a5*a6);
  a4=(a4-a7);
  a7=arg[0]? arg[0][0] : 0;
  a8=arg[5]? arg[5][15] : 0;
  a9=(a7*a8);
  a4=(a4+a9);
  a9=arg[5]? arg[5][0] : 0;
  a10=(a2*a9);
  a11=arg[5]? arg[5][1] : 0;
  a12=(a5*a11);
  a10=(a10-a12);
  a12=arg[5]? arg[5][3] : 0;
  a13=(a7*a12);
  a10=(a10+a13);
  a13=casadi_sq(a10);
  a14=(a5*a9);
  a15=(a2*a11);
  a14=(a14+a15);
  a15=arg[0]? arg[0][1] : 0;
  a16=(a15*a12);
  a14=(a14+a16);
  a16=casadi_sq(a14);
  a13=(a13+a16);
  a16=arg[5]? arg[5][2] : 0;
  a17=casadi_sq(a16);
  a13=(a13+a17);
  a17=casadi_sq(a12);
  a13=(a13+a17);
  a13=sqrt(a13);
  a17=(a10/a13);
  a18=(a4*a17);
  a19=(a5*a3);
  a20=(a2*a6);
  a19=(a19+a20);
  a20=(a15*a8);
  a19=(a19+a20);
  a20=(a14/a13);
  a21=(a19*a20);
  a18=(a18+a21);
  a21=arg[5]? arg[5][14] : 0;
  a16=(a16/a13);
  a22=(a21*a16);
  a18=(a18+a22);
  a22=(a12/a13);
  a23=(a8*a22);
  a18=(a18+a23);
  a23=(a18*a17);
  a23=(a4-a23);
  a24=arg[5]? arg[5][4] : 0;
  a25=(a2*a24);
  a26=arg[5]? arg[5][5] : 0;
  a27=(a5*a26);
  a25=(a25-a27);
  a27=arg[5]? arg[5][7] : 0;
  a28=(a7*a27);
  a25=(a25+a28);
  a28=(a25*a17);
  a29=(a5*a24);
  a30=(a2*a26);
  a29=(a29+a30);
  a30=(a15*a27);
  a29=(a29+a30);
  a30=(a29*a20);
  a28=(a28+a30);
  a30=arg[5]? arg[5][6] : 0;
  a31=(a30*a16);
  a28=(a28+a31);
  a31=(a27*a22);
  a28=(a28+a31);
  a31=(a28*a17);
  a31=(a25-a31);
  a32=casadi_sq(a31);
  a33=(a28*a20);
  a33=(a29-a33);
  a34=casadi_sq(a33);
  a32=(a32+a34);
  a34=(a28*a16);
  a34=(a30-a34);
  a35=casadi_sq(a34);
  a32=(a32+a35);
  a35=(a28*a22);
  a35=(a27-a35);
  a36=casadi_sq(a35);
  a32=(a32+a36);
  a32=sqrt(a32);
  a36=(a31/a32);
  a37=(a23*a36);
  a38=(a18*a20);
  a38=(a19-a38);
  a39=(a33/a32);
  a40=(a38*a39);
  a37=(a37+a40);
  a40=(a18*a16);
  a40=(a21-a40);
  a41=(a34/a32);
  a42=(a40*a41);
  a37=(a37+a42);
  a42=(a18*a22);
  a42=(a8-a42);
  a43=(a35/a32);
  a44=(a42*a43);
  a37=(a37+a44);
  a44=(a37*a36);
  a44=(a23-a44);
  a45=(a37*a43);
  a45=(a42-a45);
  a46=arg[5]? arg[5][8] : 0;
  a47=(a2*a46);
  a48=arg[5]? arg[5][9] : 0;
  a49=(a5*a48);
  a47=(a47-a49);
  a7=(a7*a0);
  a47=(a47+a7);
  a7=(a47*a17);
  a5=(a5*a46);
  a2=(a2*a48);
  a5=(a5+a2);
  a15=(a15*a0);
  a5=(a5+a15);
  a15=(a5*a20);
  a7=(a7+a15);
  a15=arg[5]? arg[5][10] : 0;
  a2=(a15*a16);
  a7=(a7+a2);
  a2=(a0*a22);
  a7=(a7+a2);
  a2=(a7*a17);
  a2=(a47-a2);
  a49=(a2*a36);
  a50=(a7*a20);
  a50=(a5-a50);
  a51=(a50*a39);
  a49=(a49+a51);
  a51=(a7*a16);
  a51=(a15-a51);
  a52=(a51*a41);
  a49=(a49+a52);
  a52=(a7*a22);
  a52=(a0-a52);
  a53=(a52*a43);
  a49=(a49+a53);
  a53=(a49*a36);
  a53=(a2-a53);
  a54=casadi_sq(a53);
  a55=(a49*a39);
  a55=(a50-a55);
  a56=casadi_sq(a55);
  a54=(a54+a56);
  a56=(a49*a41);
  a56=(a51-a56);
  a57=casadi_sq(a56);
  a54=(a54+a57);
  a57=(a49*a43);
  a57=(a52-a57);
  a58=casadi_sq(a57);
  a54=(a54+a58);
  a54=sqrt(a54);
  a58=(a53/a54);
  a59=(a44*a58);
  a60=(a37*a39);
  a60=(a38-a60);
  a61=(a55/a54);
  a62=(a60*a61);
  a59=(a59+a62);
  a62=(a37*a41);
  a62=(a40-a62);
  a63=(a56/a54);
  a64=(a62*a63);
  a59=(a59+a64);
  a64=(a57/a54);
  a65=(a45*a64);
  a59=(a59+a65);
  a65=(a59*a64);
  a65=(a45-a65);
  a66=(a59*a58);
  a66=(a44-a66);
  a67=casadi_sq(a66);
  a68=(a59*a61);
  a68=(a60-a68);
  a69=casadi_sq(a68);
  a67=(a67+a69);
  a69=(a59*a63);
  a69=(a62-a69);
  a70=casadi_sq(a69);
  a67=(a67+a70);
  a70=casadi_sq(a65);
  a67=(a67+a70);
  a67=sqrt(a67);
  a70=(a65/a67);
  a71=(a70/a67);
  a72=1.5000000000000000e+00;
  a73=(a66/a67);
  a74=(a73/a67);
  a75=(a37*a74);
  a75=(a36-a75);
  a76=(a59*a74);
  a76=(a58-a76);
  a76=(a76/a54);
  a77=(a49*a76);
  a75=(a75-a77);
  a75=(a75/a32);
  a77=(a72*a75);
  a78=8.2549999999999998e-02;
  a79=(a68/a67);
  a80=(a79/a67);
  a81=(a37*a80);
  a81=(a39-a81);
  a82=(a59*a80);
  a82=(a61-a82);
  a82=(a82/a54);
  a83=(a49*a82);
  a81=(a81-a83);
  a81=(a81/a32);
  a83=(a78*a81);
  a77=(a77+a83);
  a83=4.1744999999999999e-01;
  a84=(a69/a67);
  a85=(a84/a67);
  a86=(a37*a85);
  a86=(a41-a86);
  a87=(a59*a85);
  a87=(a63-a87);
  a87=(a87/a54);
  a88=(a49*a87);
  a86=(a86-a88);
  a86=(a86/a32);
  a88=(a83*a86);
  a77=(a77+a88);
  a88=(a37*a71);
  a88=(a43-a88);
  a89=(a59*a71);
  a89=(a64-a89);
  a89=(a89/a54);
  a90=(a49*a89);
  a88=(a88-a90);
  a88=(a88/a32);
  a77=(a77+a88);
  a90=(a72*a76);
  a91=(a78*a82);
  a90=(a90+a91);
  a91=(a83*a87);
  a90=(a90+a91);
  a90=(a90+a89);
  a77=(a77/a90);
  a91=(a77/a90);
  a92=arg[2]? arg[2][0] : 0;
  a77=(a92*a77);
  a93=arg[4]? arg[4][0] : 0;
  a77=(a77+a93);
  a94=-17.;
  a77=(a77-a94);
  a77=(a77+a77);
  a77=(a92*a77);
  a91=(a91*a77);
  a95=(a18*a74);
  a95=(a17-a95);
  a96=(a7*a76);
  a95=(a95-a96);
  a96=(a28*a75);
  a95=(a95-a96);
  a95=(a95/a13);
  a96=(a72*a95);
  a97=(a18*a80);
  a97=(a20-a97);
  a98=(a7*a82);
  a97=(a97-a98);
  a98=(a28*a81);
  a97=(a97-a98);
  a97=(a97/a13);
  a98=(a78*a97);
  a96=(a96+a98);
  a98=(a18*a85);
  a98=(a16-a98);
  a99=(a7*a87);
  a98=(a98-a99);
  a99=(a28*a86);
  a98=(a98-a99);
  a98=(a98/a13);
  a99=(a83*a98);
  a96=(a96+a99);
  a99=(a18*a71);
  a99=(a22-a99);
  a100=(a7*a89);
  a99=(a99-a100);
  a100=(a28*a88);
  a99=(a99-a100);
  a99=(a99/a13);
  a96=(a96+a99);
  a96=(a96/a90);
  a100=(a96/a90);
  a101=arg[1]? arg[1][0] : 0;
  a96=(a101*a96);
  a102=arg[3]? arg[3][0] : 0;
  a96=(a96+a102);
  a103=267.;
  a96=(a96-a103);
  a96=(a96+a96);
  a96=(a101*a96);
  a100=(a100*a96);
  a91=(a91+a100);
  a100=(a72*a75);
  a104=(a78*a81);
  a100=(a100+a104);
  a104=5.8255000000000001e-01;
  a105=(a104*a86);
  a100=(a100+a105);
  a100=(a100+a88);
  a105=(a72*a76);
  a106=(a78*a82);
  a105=(a105+a106);
  a106=(a104*a87);
  a105=(a105+a106);
  a105=(a105+a89);
  a100=(a100/a105);
  a106=(a100/a105);
  a100=(a92*a100);
  a100=(a100+a93);
  a107=-83.;
  a100=(a100-a107);
  a100=(a100+a100);
  a100=(a92*a100);
  a106=(a106*a100);
  a108=(a72*a95);
  a109=(a78*a97);
  a108=(a108+a109);
  a109=(a104*a98);
  a108=(a108+a109);
  a108=(a108+a99);
  a108=(a108/a105);
  a109=(a108/a105);
  a108=(a101*a108);
  a108=(a108+a102);
  a108=(a108-a103);
  a108=(a108+a108);
  a108=(a101*a108);
  a109=(a109*a108);
  a106=(a106+a109);
  a109=(a91+a106);
  a103=(a72*a75);
  a110=-8.2549999999999998e-02;
  a111=(a110*a81);
  a103=(a103+a111);
  a111=(a104*a86);
  a103=(a103+a111);
  a103=(a103+a88);
  a111=(a72*a76);
  a112=(a110*a82);
  a111=(a111+a112);
  a112=(a104*a87);
  a111=(a111+a112);
  a111=(a111+a89);
  a103=(a103/a111);
  a112=(a103/a111);
  a103=(a92*a103);
  a103=(a103+a93);
  a103=(a103-a107);
  a103=(a103+a103);
  a103=(a92*a103);
  a112=(a112*a103);
  a107=(a72*a95);
  a113=(a110*a97);
  a107=(a107+a113);
  a113=(a104*a98);
  a107=(a107+a113);
  a107=(a107+a99);
  a107=(a107/a111);
  a113=(a107/a111);
  a107=(a101*a107);
  a107=(a107+a102);
  a114=333.;
  a107=(a107-a114);
  a107=(a107+a107);
  a107=(a101*a107);
  a113=(a113*a107);
  a112=(a112+a113);
  a109=(a109+a112);
  a113=(a72*a75);
  a115=(a110*a81);
  a113=(a113+a115);
  a115=(a83*a86);
  a113=(a113+a115);
  a113=(a113+a88);
  a115=(a72*a76);
  a116=(a110*a82);
  a115=(a115+a116);
  a116=(a83*a87);
  a115=(a115+a116);
  a115=(a115+a89);
  a113=(a113/a115);
  a116=(a113/a115);
  a113=(a92*a113);
  a113=(a113+a93);
  a113=(a113-a94);
  a113=(a113+a113);
  a92=(a92*a113);
  a116=(a116*a92);
  a113=(a72*a95);
  a94=(a110*a97);
  a113=(a113+a94);
  a94=(a83*a98);
  a113=(a113+a94);
  a113=(a113+a99);
  a113=(a113/a115);
  a94=(a113/a115);
  a113=(a101*a113);
  a113=(a113+a102);
  a113=(a113-a114);
  a113=(a113+a113);
  a101=(a101*a113);
  a94=(a94*a101);
  a116=(a116+a94);
  a109=(a109+a116);
  a77=(a77/a90);
  a100=(a100/a105);
  a94=(a77+a100);
  a103=(a103/a111);
  a94=(a94+a103);
  a92=(a92/a115);
  a94=(a94+a92);
  a96=(a96/a90);
  a108=(a108/a105);
  a105=(a96+a108);
  a107=(a107/a111);
  a105=(a105+a107);
  a101=(a101/a115);
  a105=(a105+a101);
  a115=(a105/a13);
  a111=(a28*a115);
  a94=(a94-a111);
  a111=(a94/a32);
  a90=(a49*a111);
  a109=(a109+a90);
  a90=(a7*a115);
  a109=(a109+a90);
  a90=(a109/a54);
  a113=(a71*a90);
  a114=(a83*a91);
  a102=(a104*a106);
  a114=(a114+a102);
  a102=(a104*a112);
  a114=(a114+a102);
  a102=(a83*a116);
  a114=(a114+a102);
  a102=(a83*a77);
  a93=(a104*a100);
  a102=(a102+a93);
  a93=(a104*a103);
  a102=(a102+a93);
  a93=(a83*a92);
  a102=(a102+a93);
  a93=(a83*a96);
  a117=(a104*a108);
  a93=(a93+a117);
  a104=(a104*a107);
  a93=(a93+a104);
  a83=(a83*a101);
  a93=(a93+a83);
  a83=(a93/a13);
  a104=(a28*a83);
  a102=(a102-a104);
  a104=(a102/a32);
  a117=(a49*a104);
  a114=(a114+a117);
  a117=(a7*a83);
  a114=(a114+a117);
  a117=(a114/a54);
  a118=(a85*a117);
  a113=(a113+a118);
  a118=(a78*a91);
  a119=(a78*a106);
  a118=(a118+a119);
  a119=(a110*a112);
  a118=(a118+a119);
  a119=(a110*a116);
  a118=(a118+a119);
  a119=(a78*a77);
  a120=(a78*a100);
  a119=(a119+a120);
  a120=(a110*a103);
  a119=(a119+a120);
  a120=(a110*a92);
  a119=(a119+a120);
  a120=(a78*a96);
  a78=(a78*a108);
  a120=(a120+a78);
  a78=(a110*a107);
  a120=(a120+a78);
  a110=(a110*a101);
  a120=(a120+a110);
  a110=(a120/a13);
  a78=(a28*a110);
  a119=(a119-a78);
  a78=(a119/a32);
  a121=(a49*a78);
  a118=(a118+a121);
  a121=(a7*a110);
  a118=(a118+a121);
  a121=(a118/a54);
  a122=(a80*a121);
  a113=(a113+a122);
  a91=(a72*a91);
  a106=(a72*a106);
  a91=(a91+a106);
  a112=(a72*a112);
  a91=(a91+a112);
  a116=(a72*a116);
  a91=(a91+a116);
  a77=(a72*a77);
  a100=(a72*a100);
  a77=(a77+a100);
  a103=(a72*a103);
  a77=(a77+a103);
  a92=(a72*a92);
  a77=(a77+a92);
  a96=(a72*a96);
  a108=(a72*a108);
  a96=(a96+a108);
  a107=(a72*a107);
  a96=(a96+a107);
  a72=(a72*a101);
  a96=(a96+a72);
  a72=(a96/a13);
  a101=(a28*a72);
  a77=(a77-a101);
  a101=(a77/a32);
  a107=(a49*a101);
  a91=(a91+a107);
  a107=(a7*a72);
  a91=(a91+a107);
  a107=(a91/a54);
  a108=(a74*a107);
  a113=(a113+a108);
  a108=(a59*a90);
  a92=(a37*a111);
  a108=(a108-a92);
  a92=(a18*a115);
  a108=(a108-a92);
  a92=(a108/a67);
  a103=(a92/a67);
  a65=(a65+a65);
  a100=(a71/a67);
  a100=(a100*a108);
  a70=(a70/a67);
  a70=(a70*a92);
  a100=(a100+a70);
  a70=(a85/a67);
  a92=(a59*a117);
  a108=(a37*a104);
  a92=(a92-a108);
  a108=(a18*a83);
  a92=(a92-a108);
  a70=(a70*a92);
  a100=(a100+a70);
  a84=(a84/a67);
  a92=(a92/a67);
  a84=(a84*a92);
  a100=(a100+a84);
  a84=(a80/a67);
  a70=(a59*a121);
  a108=(a37*a78);
  a70=(a70-a108);
  a108=(a18*a110);
  a70=(a70-a108);
  a84=(a84*a70);
  a100=(a100+a84);
  a79=(a79/a67);
  a70=(a70/a67);
  a79=(a79*a70);
  a100=(a100+a79);
  a79=(a74/a67);
  a84=(a59*a107);
  a108=(a37*a101);
  a84=(a84-a108);
  a108=(a18*a72);
  a84=(a84-a108);
  a79=(a79*a84);
  a100=(a100+a79);
  a73=(a73/a67);
  a84=(a84/a67);
  a73=(a73*a84);
  a100=(a100+a73);
  a73=(a67+a67);
  a100=(a100/a73);
  a65=(a65*a100);
  a103=(a103-a65);
  a65=(a64*a103);
  a113=(a113-a65);
  a92=(a92/a67);
  a69=(a69+a69);
  a69=(a69*a100);
  a92=(a92-a69);
  a69=(a63*a92);
  a113=(a113-a69);
  a70=(a70/a67);
  a68=(a68+a68);
  a68=(a68*a100);
  a70=(a70-a68);
  a68=(a61*a70);
  a113=(a113-a68);
  a84=(a84/a67);
  a66=(a66+a66);
  a66=(a66*a100);
  a84=(a84-a66);
  a66=(a58*a84);
  a113=(a113-a66);
  a44=(a44*a113);
  a66=(a59*a84);
  a107=(a107+a66);
  a44=(a44-a107);
  a107=(a44/a54);
  a53=(a53+a53);
  a66=(a89/a54);
  a66=(a66*a109);
  a109=(a87/a54);
  a109=(a109*a114);
  a66=(a66+a109);
  a109=(a82/a54);
  a109=(a109*a118);
  a66=(a66+a109);
  a109=(a76/a54);
  a109=(a109*a91);
  a66=(a66+a109);
  a109=(a64/a54);
  a45=(a45*a113);
  a91=(a59*a103);
  a90=(a90+a91);
  a45=(a45-a90);
  a109=(a109*a45);
  a66=(a66-a109);
  a109=(a63/a54);
  a62=(a62*a113);
  a90=(a59*a92);
  a117=(a117+a90);
  a62=(a62-a117);
  a109=(a109*a62);
  a66=(a66-a109);
  a109=(a61/a54);
  a60=(a60*a113);
  a59=(a59*a70);
  a121=(a121+a59);
  a60=(a60-a121);
  a109=(a109*a60);
  a66=(a66-a109);
  a109=(a58/a54);
  a109=(a109*a44);
  a66=(a66-a109);
  a109=(a54+a54);
  a66=(a66/a109);
  a53=(a53*a66);
  a107=(a107+a53);
  a53=(a89*a111);
  a109=(a87*a104);
  a53=(a53+a109);
  a109=(a82*a78);
  a53=(a53+a109);
  a109=(a76*a101);
  a53=(a53+a109);
  a45=(a45/a54);
  a57=(a57+a57);
  a57=(a57*a66);
  a45=(a45+a57);
  a57=(a43*a45);
  a53=(a53+a57);
  a62=(a62/a54);
  a56=(a56+a56);
  a56=(a56*a66);
  a62=(a62+a56);
  a56=(a41*a62);
  a53=(a53+a56);
  a60=(a60/a54);
  a55=(a55+a55);
  a55=(a55*a66);
  a60=(a60+a55);
  a55=(a39*a60);
  a53=(a53+a55);
  a55=(a36*a107);
  a53=(a53+a55);
  a55=(a36*a53);
  a55=(a107-a55);
  a89=(a89*a115);
  a87=(a87*a83);
  a89=(a89+a87);
  a82=(a82*a110);
  a89=(a89+a82);
  a76=(a76*a72);
  a89=(a89+a76);
  a76=(a43*a53);
  a76=(a45-a76);
  a82=(a22*a76);
  a89=(a89+a82);
  a82=(a41*a53);
  a82=(a62-a82);
  a87=(a16*a82);
  a89=(a89+a87);
  a87=(a39*a53);
  a87=(a60-a87);
  a66=(a20*a87);
  a89=(a89+a66);
  a66=(a17*a55);
  a89=(a89+a66);
  a66=(a17*a89);
  a66=(a55-a66);
  a54=(a0*a66);
  a107=(a49*a107);
  a107=(a101-a107);
  a2=(a2*a53);
  a107=(a107-a2);
  a58=(a58*a113);
  a84=(a84+a58);
  a58=(a37*a84);
  a107=(a107-a58);
  a58=(a71*a111);
  a2=(a85*a104);
  a58=(a58+a2);
  a2=(a80*a78);
  a58=(a58+a2);
  a101=(a74*a101);
  a58=(a58+a101);
  a64=(a64*a113);
  a103=(a103+a64);
  a64=(a43*a103);
  a58=(a58+a64);
  a63=(a63*a113);
  a92=(a92+a63);
  a63=(a41*a92);
  a58=(a58+a63);
  a61=(a61*a113);
  a70=(a70+a61);
  a61=(a39*a70);
  a58=(a58+a61);
  a61=(a36*a84);
  a58=(a58+a61);
  a23=(a23*a58);
  a107=(a107-a23);
  a23=(a107/a32);
  a31=(a31+a31);
  a61=(a88/a32);
  a61=(a61*a94);
  a94=(a86/a32);
  a94=(a94*a102);
  a61=(a61+a94);
  a94=(a81/a32);
  a94=(a94*a119);
  a61=(a61+a94);
  a94=(a75/a32);
  a94=(a94*a77);
  a61=(a61+a94);
  a94=(a43/a32);
  a77=(a37*a103);
  a111=(a111-a77);
  a45=(a49*a45);
  a111=(a111-a45);
  a52=(a52*a53);
  a111=(a111-a52);
  a42=(a42*a58);
  a111=(a111-a42);
  a94=(a94*a111);
  a61=(a61+a94);
  a94=(a41/a32);
  a42=(a37*a92);
  a104=(a104-a42);
  a62=(a49*a62);
  a104=(a104-a62);
  a51=(a51*a53);
  a104=(a104-a51);
  a40=(a40*a58);
  a104=(a104-a40);
  a94=(a94*a104);
  a61=(a61+a94);
  a94=(a39/a32);
  a37=(a37*a70);
  a78=(a78-a37);
  a49=(a49*a60);
  a78=(a78-a49);
  a50=(a50*a53);
  a78=(a78-a50);
  a38=(a38*a58);
  a78=(a78-a38);
  a94=(a94*a78);
  a61=(a61+a94);
  a94=(a36/a32);
  a94=(a94*a107);
  a61=(a61+a94);
  a94=(a32+a32);
  a61=(a61/a94);
  a31=(a31*a61);
  a23=(a23-a31);
  a88=(a88*a115);
  a86=(a86*a83);
  a88=(a88+a86);
  a81=(a81*a110);
  a88=(a88+a81);
  a75=(a75*a72);
  a88=(a88+a75);
  a111=(a111/a32);
  a35=(a35+a35);
  a35=(a35*a61);
  a111=(a111-a35);
  a35=(a22*a111);
  a88=(a88+a35);
  a104=(a104/a32);
  a34=(a34+a34);
  a34=(a34*a61);
  a104=(a104-a34);
  a34=(a16*a104);
  a88=(a88+a34);
  a78=(a78/a32);
  a33=(a33+a33);
  a33=(a33*a61);
  a78=(a78-a33);
  a33=(a20*a78);
  a88=(a88+a33);
  a33=(a17*a23);
  a88=(a88+a33);
  a33=(a17*a88);
  a33=(a23-a33);
  a61=(a27*a33);
  a54=(a54+a61);
  a36=(a36*a58);
  a84=(a84-a36);
  a71=(a71*a115);
  a85=(a85*a83);
  a71=(a71+a85);
  a80=(a80*a110);
  a71=(a71+a80);
  a74=(a74*a72);
  a71=(a71+a74);
  a43=(a43*a58);
  a103=(a103-a43);
  a43=(a22*a103);
  a71=(a71+a43);
  a41=(a41*a58);
  a92=(a92-a41);
  a41=(a16*a92);
  a71=(a71+a41);
  a39=(a39*a58);
  a70=(a70-a39);
  a39=(a20*a70);
  a71=(a71+a39);
  a39=(a17*a84);
  a71=(a71+a39);
  a39=(a17*a71);
  a39=(a84-a39);
  a58=(a8*a39);
  a54=(a54+a58);
  a55=(a7*a55);
  a72=(a72-a55);
  a47=(a47*a89);
  a72=(a72-a47);
  a23=(a28*a23);
  a72=(a72-a23);
  a25=(a25*a88);
  a72=(a72-a25);
  a84=(a18*a84);
  a72=(a72-a84);
  a4=(a4*a71);
  a72=(a72-a4);
  a4=(a72/a13);
  a10=(a10+a10);
  a99=(a99/a13);
  a99=(a99*a105);
  a98=(a98/a13);
  a98=(a98*a93);
  a99=(a99+a98);
  a97=(a97/a13);
  a97=(a97*a120);
  a99=(a99+a97);
  a95=(a95/a13);
  a95=(a95*a96);
  a99=(a99+a95);
  a22=(a22/a13);
  a76=(a7*a76);
  a115=(a115-a76);
  a76=(a0*a89);
  a115=(a115-a76);
  a103=(a18*a103);
  a115=(a115-a103);
  a111=(a28*a111);
  a115=(a115-a111);
  a111=(a27*a88);
  a115=(a115-a111);
  a111=(a8*a71);
  a115=(a115-a111);
  a22=(a22*a115);
  a99=(a99+a22);
  a16=(a16/a13);
  a82=(a7*a82);
  a83=(a83-a82);
  a15=(a15*a89);
  a83=(a83-a15);
  a92=(a18*a92);
  a83=(a83-a92);
  a104=(a28*a104);
  a83=(a83-a104);
  a30=(a30*a88);
  a83=(a83-a30);
  a21=(a21*a71);
  a83=(a83-a21);
  a16=(a16*a83);
  a99=(a99+a16);
  a16=(a20/a13);
  a7=(a7*a87);
  a110=(a110-a7);
  a5=(a5*a89);
  a110=(a110-a5);
  a18=(a18*a70);
  a110=(a110-a18);
  a28=(a28*a78);
  a110=(a110-a28);
  a29=(a29*a88);
  a110=(a110-a29);
  a19=(a19*a71);
  a110=(a110-a19);
  a16=(a16*a110);
  a99=(a99+a16);
  a17=(a17/a13);
  a17=(a17*a72);
  a99=(a99+a17);
  a17=(a13+a13);
  a99=(a99/a17);
  a10=(a10*a99);
  a4=(a4-a10);
  a10=(a12*a4);
  a54=(a54+a10);
  if (res[0]!=0) res[0][0]=a54;
  a89=(a20*a89);
  a87=(a87-a89);
  a0=(a0*a87);
  a88=(a20*a88);
  a78=(a78-a88);
  a27=(a27*a78);
  a0=(a0+a27);
  a20=(a20*a71);
  a70=(a70-a20);
  a8=(a8*a70);
  a0=(a0+a8);
  a110=(a110/a13);
  a14=(a14+a14);
  a14=(a14*a99);
  a110=(a110-a14);
  a12=(a12*a110);
  a0=(a0+a12);
  if (res[0]!=0) res[0][1]=a0;
  a0=cos(a1);
  a12=(a46*a87);
  a14=(a48*a66);
  a12=(a12-a14);
  a14=(a24*a78);
  a12=(a12+a14);
  a14=(a26*a33);
  a12=(a12-a14);
  a14=(a3*a70);
  a12=(a12+a14);
  a14=(a6*a39);
  a12=(a12-a14);
  a14=(a9*a110);
  a12=(a12+a14);
  a14=(a11*a4);
  a12=(a12-a14);
  a0=(a0*a12);
  a1=sin(a1);
  a48=(a48*a87);
  a46=(a46*a66);
  a48=(a48+a46);
  a26=(a26*a78);
  a48=(a48+a26);
  a24=(a24*a33);
  a48=(a48+a24);
  a6=(a6*a70);
  a48=(a48+a6);
  a3=(a3*a39);
  a48=(a48+a3);
  a11=(a11*a110);
  a48=(a48+a11);
  a9=(a9*a4);
  a48=(a48+a9);
  a1=(a1*a48);
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int grad_J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void grad_J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int grad_J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void grad_J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void grad_J_incref(void) {
}

CASADI_SYMBOL_EXPORT void grad_J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int grad_J_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int grad_J_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real grad_J_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* grad_J_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* grad_J_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* grad_J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* grad_J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int grad_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
