/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) J_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[15] = {2, 4, 0, 2, 4, 6, 8, 0, 1, 0, 1, 0, 1, 0, 1};

/* J:(i0[3],i1,i2,i3,i4,i5[4x4],i6[4x4],i7[2x4])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[5]? arg[5][0] : 0;
  a4=(a2*a3);
  a1=sin(a1);
  a5=arg[5]? arg[5][1] : 0;
  a6=(a1*a5);
  a4=(a4-a6);
  a6=arg[0]? arg[0][0] : 0;
  a7=arg[5]? arg[5][3] : 0;
  a8=(a6*a7);
  a4=(a4+a8);
  a8=casadi_sq(a4);
  a3=(a1*a3);
  a5=(a2*a5);
  a3=(a3+a5);
  a5=arg[0]? arg[0][1] : 0;
  a9=(a5*a7);
  a3=(a3+a9);
  a9=casadi_sq(a3);
  a8=(a8+a9);
  a9=arg[5]? arg[5][2] : 0;
  a10=casadi_sq(a9);
  a8=(a8+a10);
  a10=casadi_sq(a7);
  a8=(a8+a10);
  a8=sqrt(a8);
  a4=(a4/a8);
  a10=arg[5]? arg[5][12] : 0;
  a11=(a2*a10);
  a12=arg[5]? arg[5][13] : 0;
  a13=(a1*a12);
  a11=(a11-a13);
  a13=arg[5]? arg[5][15] : 0;
  a14=(a6*a13);
  a11=(a11+a14);
  a14=(a11*a4);
  a10=(a1*a10);
  a12=(a2*a12);
  a10=(a10+a12);
  a12=(a5*a13);
  a10=(a10+a12);
  a3=(a3/a8);
  a12=(a10*a3);
  a14=(a14+a12);
  a12=arg[5]? arg[5][14] : 0;
  a9=(a9/a8);
  a15=(a12*a9);
  a14=(a14+a15);
  a7=(a7/a8);
  a15=(a13*a7);
  a14=(a14+a15);
  a15=(a14*a4);
  a11=(a11-a15);
  a15=arg[5]? arg[5][4] : 0;
  a16=(a2*a15);
  a17=arg[5]? arg[5][5] : 0;
  a18=(a1*a17);
  a16=(a16-a18);
  a18=arg[5]? arg[5][7] : 0;
  a19=(a6*a18);
  a16=(a16+a19);
  a19=(a16*a4);
  a15=(a1*a15);
  a17=(a2*a17);
  a15=(a15+a17);
  a17=(a5*a18);
  a15=(a15+a17);
  a17=(a15*a3);
  a19=(a19+a17);
  a17=arg[5]? arg[5][6] : 0;
  a20=(a17*a9);
  a19=(a19+a20);
  a20=(a18*a7);
  a19=(a19+a20);
  a20=(a19*a4);
  a16=(a16-a20);
  a20=casadi_sq(a16);
  a21=(a19*a3);
  a15=(a15-a21);
  a21=casadi_sq(a15);
  a20=(a20+a21);
  a21=(a19*a9);
  a17=(a17-a21);
  a21=casadi_sq(a17);
  a20=(a20+a21);
  a21=(a19*a7);
  a18=(a18-a21);
  a21=casadi_sq(a18);
  a20=(a20+a21);
  a20=sqrt(a20);
  a16=(a16/a20);
  a21=(a11*a16);
  a22=(a14*a3);
  a10=(a10-a22);
  a15=(a15/a20);
  a22=(a10*a15);
  a21=(a21+a22);
  a22=(a14*a9);
  a12=(a12-a22);
  a17=(a17/a20);
  a22=(a12*a17);
  a21=(a21+a22);
  a22=(a14*a7);
  a13=(a13-a22);
  a18=(a18/a20);
  a22=(a13*a18);
  a21=(a21+a22);
  a22=(a21*a16);
  a11=(a11-a22);
  a22=arg[5]? arg[5][8] : 0;
  a23=(a2*a22);
  a24=arg[5]? arg[5][9] : 0;
  a25=(a1*a24);
  a23=(a23-a25);
  a25=arg[5]? arg[5][11] : 0;
  a6=(a6*a25);
  a23=(a23+a6);
  a6=(a23*a4);
  a1=(a1*a22);
  a2=(a2*a24);
  a1=(a1+a2);
  a5=(a5*a25);
  a1=(a1+a5);
  a5=(a1*a3);
  a6=(a6+a5);
  a5=arg[5]? arg[5][10] : 0;
  a2=(a5*a9);
  a6=(a6+a2);
  a2=(a25*a7);
  a6=(a6+a2);
  a2=(a6*a4);
  a23=(a23-a2);
  a2=(a23*a16);
  a24=(a6*a3);
  a1=(a1-a24);
  a24=(a1*a15);
  a2=(a2+a24);
  a24=(a6*a9);
  a5=(a5-a24);
  a24=(a5*a17);
  a2=(a2+a24);
  a24=(a6*a7);
  a25=(a25-a24);
  a24=(a25*a18);
  a2=(a2+a24);
  a24=(a2*a16);
  a23=(a23-a24);
  a24=casadi_sq(a23);
  a22=(a2*a15);
  a1=(a1-a22);
  a22=casadi_sq(a1);
  a24=(a24+a22);
  a22=(a2*a17);
  a5=(a5-a22);
  a22=casadi_sq(a5);
  a24=(a24+a22);
  a22=(a2*a18);
  a25=(a25-a22);
  a22=casadi_sq(a25);
  a24=(a24+a22);
  a24=sqrt(a24);
  a23=(a23/a24);
  a22=(a11*a23);
  a26=(a21*a15);
  a10=(a10-a26);
  a1=(a1/a24);
  a26=(a10*a1);
  a22=(a22+a26);
  a26=(a21*a17);
  a12=(a12-a26);
  a5=(a5/a24);
  a26=(a12*a5);
  a22=(a22+a26);
  a26=(a21*a18);
  a13=(a13-a26);
  a25=(a25/a24);
  a26=(a13*a25);
  a22=(a22+a26);
  a26=(a22*a23);
  a11=(a11-a26);
  a26=casadi_sq(a11);
  a27=(a22*a1);
  a10=(a10-a27);
  a27=casadi_sq(a10);
  a26=(a26+a27);
  a27=(a22*a5);
  a12=(a12-a27);
  a27=casadi_sq(a12);
  a26=(a26+a27);
  a27=(a22*a25);
  a13=(a13-a27);
  a27=casadi_sq(a13);
  a26=(a26+a27);
  a26=sqrt(a26);
  a11=(a11/a26);
  a11=(a11/a26);
  a27=(a14*a11);
  a4=(a4-a27);
  a27=(a22*a11);
  a23=(a23-a27);
  a23=(a23/a24);
  a27=(a6*a23);
  a4=(a4-a27);
  a11=(a21*a11);
  a16=(a16-a11);
  a11=(a2*a23);
  a16=(a16-a11);
  a16=(a16/a20);
  a11=(a19*a16);
  a4=(a4-a11);
  a4=(a4/a8);
  a11=arg[6]? arg[6][0] : 0;
  a27=(a4*a11);
  a10=(a10/a26);
  a10=(a10/a26);
  a28=(a14*a10);
  a3=(a3-a28);
  a28=(a22*a10);
  a1=(a1-a28);
  a1=(a1/a24);
  a28=(a6*a1);
  a3=(a3-a28);
  a10=(a21*a10);
  a15=(a15-a10);
  a10=(a2*a1);
  a15=(a15-a10);
  a15=(a15/a20);
  a10=(a19*a15);
  a3=(a3-a10);
  a3=(a3/a8);
  a10=arg[6]? arg[6][1] : 0;
  a28=(a3*a10);
  a27=(a27+a28);
  a12=(a12/a26);
  a12=(a12/a26);
  a28=(a14*a12);
  a9=(a9-a28);
  a28=(a22*a12);
  a5=(a5-a28);
  a5=(a5/a24);
  a28=(a6*a5);
  a9=(a9-a28);
  a12=(a21*a12);
  a17=(a17-a12);
  a12=(a2*a5);
  a17=(a17-a12);
  a17=(a17/a20);
  a12=(a19*a17);
  a9=(a9-a12);
  a9=(a9/a8);
  a12=arg[6]? arg[6][2] : 0;
  a28=(a9*a12);
  a27=(a27+a28);
  a13=(a13/a26);
  a13=(a13/a26);
  a14=(a14*a13);
  a7=(a7-a14);
  a22=(a22*a13);
  a25=(a25-a22);
  a25=(a25/a24);
  a6=(a6*a25);
  a7=(a7-a6);
  a21=(a21*a13);
  a18=(a18-a21);
  a2=(a2*a25);
  a18=(a18-a2);
  a18=(a18/a20);
  a19=(a19*a18);
  a7=(a7-a19);
  a7=(a7/a8);
  a8=arg[6]? arg[6][3] : 0;
  a19=(a7*a8);
  a27=(a27+a19);
  a19=(a23*a11);
  a20=(a1*a10);
  a19=(a19+a20);
  a20=(a5*a12);
  a19=(a19+a20);
  a20=(a25*a8);
  a19=(a19+a20);
  a27=(a27/a19);
  a27=(a0*a27);
  a20=arg[3]? arg[3][0] : 0;
  a27=(a27+a20);
  a2=arg[7]? arg[7][0] : 0;
  a27=(a27-a2);
  a27=casadi_sq(a27);
  a2=arg[6]? arg[6][4] : 0;
  a21=(a4*a2);
  a13=arg[6]? arg[6][5] : 0;
  a6=(a3*a13);
  a21=(a21+a6);
  a6=arg[6]? arg[6][6] : 0;
  a24=(a9*a6);
  a21=(a21+a24);
  a24=arg[6]? arg[6][7] : 0;
  a22=(a7*a24);
  a21=(a21+a22);
  a22=(a23*a2);
  a14=(a1*a13);
  a22=(a22+a14);
  a14=(a5*a6);
  a22=(a22+a14);
  a14=(a25*a24);
  a22=(a22+a14);
  a21=(a21/a22);
  a21=(a0*a21);
  a21=(a21+a20);
  a14=arg[7]? arg[7][2] : 0;
  a21=(a21-a14);
  a21=casadi_sq(a21);
  a27=(a27+a21);
  a21=arg[6]? arg[6][8] : 0;
  a14=(a4*a21);
  a26=arg[6]? arg[6][9] : 0;
  a28=(a3*a26);
  a14=(a14+a28);
  a28=arg[6]? arg[6][10] : 0;
  a29=(a9*a28);
  a14=(a14+a29);
  a29=arg[6]? arg[6][11] : 0;
  a30=(a7*a29);
  a14=(a14+a30);
  a30=(a23*a21);
  a31=(a1*a26);
  a30=(a30+a31);
  a31=(a5*a28);
  a30=(a30+a31);
  a31=(a25*a29);
  a30=(a30+a31);
  a14=(a14/a30);
  a14=(a0*a14);
  a14=(a14+a20);
  a31=arg[7]? arg[7][4] : 0;
  a14=(a14-a31);
  a14=casadi_sq(a14);
  a27=(a27+a14);
  a14=arg[6]? arg[6][12] : 0;
  a4=(a4*a14);
  a31=arg[6]? arg[6][13] : 0;
  a3=(a3*a31);
  a4=(a4+a3);
  a3=arg[6]? arg[6][14] : 0;
  a9=(a9*a3);
  a4=(a4+a9);
  a9=arg[6]? arg[6][15] : 0;
  a7=(a7*a9);
  a4=(a4+a7);
  a23=(a23*a14);
  a1=(a1*a31);
  a23=(a23+a1);
  a5=(a5*a3);
  a23=(a23+a5);
  a25=(a25*a9);
  a23=(a23+a25);
  a4=(a4/a23);
  a0=(a0*a4);
  a0=(a0+a20);
  a20=arg[7]? arg[7][6] : 0;
  a0=(a0-a20);
  a0=casadi_sq(a0);
  a27=(a27+a0);
  a0=arg[2]? arg[2][0] : 0;
  a11=(a16*a11);
  a10=(a15*a10);
  a11=(a11+a10);
  a12=(a17*a12);
  a11=(a11+a12);
  a8=(a18*a8);
  a11=(a11+a8);
  a11=(a11/a19);
  a11=(a0*a11);
  a19=arg[4]? arg[4][0] : 0;
  a11=(a11+a19);
  a8=arg[7]? arg[7][1] : 0;
  a11=(a11-a8);
  a11=casadi_sq(a11);
  a2=(a16*a2);
  a13=(a15*a13);
  a2=(a2+a13);
  a6=(a17*a6);
  a2=(a2+a6);
  a24=(a18*a24);
  a2=(a2+a24);
  a2=(a2/a22);
  a2=(a0*a2);
  a2=(a2+a19);
  a22=arg[7]? arg[7][3] : 0;
  a2=(a2-a22);
  a2=casadi_sq(a2);
  a11=(a11+a2);
  a21=(a16*a21);
  a26=(a15*a26);
  a21=(a21+a26);
  a28=(a17*a28);
  a21=(a21+a28);
  a29=(a18*a29);
  a21=(a21+a29);
  a21=(a21/a30);
  a21=(a0*a21);
  a21=(a21+a19);
  a30=arg[7]? arg[7][5] : 0;
  a21=(a21-a30);
  a21=casadi_sq(a21);
  a11=(a11+a21);
  a16=(a16*a14);
  a15=(a15*a31);
  a16=(a16+a15);
  a17=(a17*a3);
  a16=(a16+a17);
  a18=(a18*a9);
  a16=(a16+a18);
  a16=(a16/a23);
  a0=(a0*a16);
  a0=(a0+a19);
  a19=arg[7]? arg[7][7] : 0;
  a0=(a0-a19);
  a0=casadi_sq(a0);
  a11=(a11+a0);
  a27=(a27+a11);
  if (res[0]!=0) res[0][0]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void J_incref(void) {
}

CASADI_SYMBOL_EXPORT void J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int J_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int J_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real J_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s2;
    case 6: return casadi_s2;
    case 7: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
